apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mharko/frontend:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
          - |
            find /usr/share/nginx/html -name '*.js' -exec sed -i "s|http://192.168.49.2:31000|${KEYCLOAK_URL}|g" {} + && find /usr/share/nginx/html -name '*.js' -exec sed -i "s|http://localhost:8090|${BACKEND_URL}|g" {} + && nginx -g "daemon off;"
        env:
        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: global-config-prod
              key: KEYCLOAK_URL
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: global-config-prod
              key: BACKEND_URL
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31111