sonar.projectKey=ToolRent-Frontend
sonar.projectName=ToolRent-Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqp_6fa5f6392d9cc308b22f4d320b18540035693cea

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.exclusions=**/*.test.js,**/*.test.jsx,**/*.css,**/*.py,Dockerfile,index.html
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
