apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: toolrent

build:
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    gitCommit:
      ignoreChanges: true
  artifacts:
    - image: mharko/toolrent-service
      context: Backend/demo
      jib:
        type: gradle

    - image: mharko/frontend
      context: Frontend/my-app
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - Kubernetes-Config/**/*.yaml

deploy:
  kubectl: {}

profiles:
  - name: prod
    build:
      local:
        push: true
      artifacts:
        - image: mharko/frontend
          context: Frontend/my-app
          docker:
            dockerfile: Dockerfile
            buildArgs:
              VITE_BACKEND_SERVER: "54.207.116.60"
              VITE_BACKEND_PORT: "80"
    manifests:
      rawYaml:
        - Kubernetes-Config-Prod/**/*.yaml