---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA9TJiVbEoJWxwnLZZkaTI+Qd48AZAmh++Cz7xEREQ5p5ZDkf05kvdC3VgTY2xWQIOzZIg1axvbVnuP/lidPDVbZr/9NMANvh2TIr30E77dJNrdhC32qU1do7TuWjVNjglTfkhhUyBAYvrtO3teYsqYGCRUr4sctvTDhQBqINlHTWFjco6lN8iKCRHLsO/nG3/fMe+bv89ycYEMX5vXYAnudoM22gW+BIdFy1ntdnqLfPoUkaUbArgJ6wOuoxbxvXMO3NwcQFzYmtkII3f5rFb+QgkKyNMIHRxjUbgaP9QNYmkw19xrGYC6casJkkKkSkUnAh5SsLWlijrxmJoo49ojVp5SXVh+IQCzUQYXOfLJRAozep3JxiufsTY3QCkHh/+z0xN2cSLv3ecMVNyXsBdXeC8jYL/lJEWKDcXg61jP2aT8s0vq2JX1fADLKcMdTwF2vfsdOMr6zO464/JGaLVOsBV+x8zM7U5XEuY4/pN13bznAM1t6/vbeic66t//YHPNEbPddtgkSlCzcj50gLiUKDrYpgJkl205y8DV8jM05VIc6JsZIsD+l3hOihyajpmW2r8RC+8pwSG3McTs9KKkvSvN7dvns3z0gfWtgBUEw8uQgXESAr9bW7WW5VuNuXJ8Lc9d+FkoDyItD5ZHtjynL4riYSqF4BWlc103WMY1knfM1m7lKdTr2dnyvYTU5GfSfLlT
  template:
    metadata:
      name: db-credentials
      namespace: default
