---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAyDnRlWVbXmdn+OlXHhTsxYunohOokeRZNPjmNvPHdNc7S5TjfQJHhid2nLtZLUNrdoqGFS4yhmbClFpIHmFiwWvi4z/UrZtuQrFW26u4FHbl8qPewl5/32XAXFimV65bmhpJCGZmL6wke+UKlVK2prWVp4O4YmRs9G/S8NGCPaSdKO/Kvwv7TEIY5DIuYKwe3JcwEZ3AS/u/HTH4l7yDqvaM2qDOkZgMWUyjyGIfvPgXHOqTm5GxYf+LFkd4ompeOXDCYTG3vEUwua1BRYcd406yJ29o7JC1colLP5myCSaj932IlLATI5Nc9NgmULfdpK5XAazqSh2Po6ODwZS6JL+izTX+Xr43bty+kmVS+8PgEPsdYcs02FIgMUd5PTGbG2cwJRPXHt3g9K3bEg7Taw3nNwQI3o4sO7yxPYCAbZSWgtSng6PZjU5ibOrbeKPWQGCizUONKoUJrDnVhmpPXTeaXHzRcqJNxD7sk9fKk0dPjGTEE0A4NdY2ppBnW5w0amcvNogSSgjl6lQZLSBuTAFUnKCmtLN3mLN2bJR5uQVSQyymxhp6J5E4LtKPOFW+aQPQNuycv8jSrIjICMFy/g+0QoMPZrLMk+Jfm9fO2c6SqZTNZGz++ivm6Dw5wJksdVr0jPKNj+Rvie6WR1moNuYgVXJ1SU8Y7aEQhNbRzFTsydOsJQkTI9awT3S1KoHOeVyI3
  template:
    metadata:
      name: db-credentials
      namespace: default
