---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCxRdpwdLM8gLHOiS6ve/6y0N9LrfV1UpEZgXU/vs/8lf6COLhXdL8GX1GQBlgFKxC2PXsmX4heXz82fvKCcTlhya4UuX+4MwVPgqTzVsVVEd66FnfF7mN1C3ifkubvjRIf8IEMrXQ4JBfhrO2oYYqLTpJLIUJQ7Phm21e0XRIj+wneS7zRRByab8slBxCzMqMIn5q6yZOuhBD52EIZ/NBUTdE9jqHnb003AHXAgwzYXqkLiaCL7In6NNpJ46gQ51f4GXLqyOU6mdPDwtZeXTOZdshesefUT3m/ztCumcgQkyC4dfeEDFSyPoFXSiR4PLVpNijVdSViNlC9iaISr0G1jOgkxLHQzVbzev0FA5DYhGwB5k2R0NyJ/QA4zan+yhPZKwlHSMKVu3C2EzgXbatviJGNrYUB6fZYJU2EY0GOKFLMGVo5RUm1HQwQ0DF6uHyTqpXmq7jwNbKWeBt7Um8ifdAmU5NcGNI8FXxsO+3EJcnUmXuKBQb9IW1eFpMSugNeZwZzAurKxxJkECJl+nIxgh93hdD9f9swMrj97G9ZtrFLm5DyTR8OR++zYRF8qVp8zUlb6gtUURD1K/+4pdtSIyrjlck5QqKzAbrJPbgJqoKBdeKFmD0uqHFgzcCXJ2/YYgGhj0JL7Fypeh2Rnri/vaJued9ZDj7rsEj1oopoOgmVOhczerMOz2zlKhv4N1zEjUln
  template:
    metadata:
      name: db-credentials
      namespace: default
